version: '3.9'

services:
  server-build:
    build: ./server
    image: load-balancer-project_server-build:latest
    container_name: server_build_temp
    command: ["echo", "Server image built successfully"]
    networks:
      - net1

  load-balancer:
    build: ./load-balancer
    container_name: load_balancer
    ports:
      - "5000:5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
    networks:
      net1:
        aliases:
          - load-balancer
    depends_on:
      - server-build
    restart: unless-stopped

networks:
  net1:
    driver: bridge